# Matrices et calculs pour les états de Bell

### Jean-Michel Torres, IBM Q Hub France, torresjm@fr.ibm.com



In [1]:
import numpy as np
from math import sqrt

In [8]:
CNOT = np.matrix(((1,0,0,0),(0,1,0,0),(0,0,0,1),(0,0,1,0)))
H = np.matrix(((1,1),(1,-1)))
I = np.matrix(((1,0),(0,1)))

HoI = np.kron(H,I)

print("HoI: \n",HoI, '\n')
Bell = np.matmul(CNOT,HoI)
print("Bell: \n",Bell, '\n')

kets = np.zeros((4,4))
np.fill_diagonal(kets,1)


bell =[]

for i in range(4):
    print(f"Ket{i:0>2b} : {kets[i]} => Bell {i:0>2b} : {np.matmul(Bell,np.transpose(kets[i]))}")
    bell.append(np.matmul(Bell,np.transpose(kets[i])))


HoI: 
 [[ 1  0  1  0]
 [ 0  1  0  1]
 [ 1  0 -1  0]
 [ 0  1  0 -1]] 

Bell: 
 [[ 1  0  1  0]
 [ 0  1  0  1]
 [ 0  1  0 -1]
 [ 1  0 -1  0]] 

Ket00 : [1. 0. 0. 0.] => Bell 00 : [[1. 0. 0. 1.]]
Ket01 : [0. 1. 0. 0.] => Bell 01 : [[0. 1. 1. 0.]]
Ket10 : [0. 0. 1. 0.] => Bell 10 : [[ 1.  0.  0. -1.]]
Ket11 : [0. 0. 0. 1.] => Bell 11 : [[ 0.  1. -1.  0.]]


In [7]:
BellDagger = np.transpose(Bell)
print(BellDagger, '\n')


for i in range(4):
    print(f"Bell{i:0>2b}: {bell[i]} (ij={i:0>2b}): {np.transpose(np.matmul(BellDagger,np.transpose(bell[i])))}")


[[ 1  0  0  1]
 [ 0  1  1  0]
 [ 1  0  0 -1]
 [ 0  1 -1  0]] 

Bell00: [[1. 0. 0. 1.]] (ij=00): [[2. 0. 0. 0.]]
Bell01: [[0. 1. 1. 0.]] (ij=01): [[0. 2. 0. 0.]]
Bell10: [[ 1.  0.  0. -1.]] (ij=10): [[0. 0. 2. 0.]]
Bell11: [[ 0.  1. -1.  0.]] (ij=11): [[0. 0. 0. 2.]]
